import { apollo_logo } from "../imagepath";

export const hospitalDetails = [
    {
      id: 1,
      name: "Apollo",
      logo: apollo_logo,
      status: "Active",
      totalFasttags: 30,
      todayBookings: 221,
    },
    {
      id: 2,
      name: "Apollo",
      logo: apollo_logo,
      status: "Active",
      totalFasttags: 30,
      todayBookings: 221,
    },
    {
      id: 3,
      name: "Apollo",
      logo: apollo_logo,
      status: "Active",
      totalFasttags: 30,
      todayBookings: 221,
    },
    {
      id: 4,
      name: "Apollo",
      logo: apollo_logo,
      status: "Active",
      totalFasttags: 30,
      todayBookings: 221,
    },
    {
      id: 5,
      name: "Apollo",
      logo: apollo_logo,
      status: "Active",
      totalFasttags: 30,
      todayBookings: 221,
    },
    {
      id: 6,
      name: "Apollo",
      logo: apollo_logo,
      status: "Active",
      totalFasttags: 30,
      todayBookings: 221,
    },
    {
      id: 7,
      name: "Apollo",
      logo: apollo_logo,
      status: "Active",
      totalFasttags: 30,
      todayBookings: 221,
    },
    {
      id: 8,
      name: "Apollo",
      logo: apollo_logo,
      status: "Active",
      totalFasttags: 30,
      todayBookings: 221,
    },
    {
      id: 9,
      name: "Apollo",
      logo: apollo_logo,
      status: "Active",
      totalFasttags: 30,
      todayBookings: 221,
    },{
      id: 10,
      name: "Apollo",
      logo: apollo_logo,
      status: "Active",
      totalFasttags: 30,
      todayBookings: 221,
    },{
      id:11,
      name: "Apollo",
      logo: apollo_logo,
      status: "Active",
      totalFasttags: 30,
      todayBookings: 221,
    },{
      id: 12,
      name: "Apollo",
      logo: apollo_logo,
      status: "Active",
      totalFasttags: 30,
      todayBookings: 221,
    },
  ];